export * from "./pkg/agents_are_thinking_js";
import type {
  BarBounce as BarBounceT, BarSeeSaw as BarSeeSawT, BarWave as BarWaveT,
  BrailleArrow as BrailleArrowT, BrailleBounce as BrailleBounceT, BrailleBreathe as BrailleBreatheT,
  BrailleCheckerboard as BrailleCheckerboardT, BrailleCheckerboard2x2 as BrailleCheckerboard2x2T,
  BrailleDissolve as BrailleDissolveT, BrailleFire as BrailleFireT, BrailleHeartbeat as BrailleHeartbeatT,
  BrailleMatrix as BrailleMatrixT, BrailleNoise as BrailleNoiseT, BrailleRain as BrailleRainT,
  BrailleRandom as BrailleRandomT, BrailleRipple as BrailleRippleT, BrailleScanner as BrailleScannerT,
  BrailleSpin as BrailleSpinT, BrailleSpin2 as BrailleSpin2T, BrailleWave as BrailleWaveT,
  BrailleZigzag as BrailleZigzagT,
  DotArrow as DotArrowT, DotBounce as DotBounceT, DotHeartbeat as DotHeartbeatT,
  DotPulse as DotPulseT, DotWave as DotWaveT,
  ShadeBlink as ShadeBlinkT, ShadeBreathe as ShadeBreatheT, ShadeFire as ShadeFireT,
  ShadeLayers as ShadeLayersT, ShadePinch as ShadePinchT, ShadeRipple as ShadeRippleT,
  ShadeScanner as ShadeScannerT, ShadeSeeSaw as ShadeSeeSawT, ShadeWave as ShadeWaveT,
  SquareArrow as SquareArrowT, SquareBlink as SquareBlinkT, SquareFill as SquareFillT,
  SquarePulse as SquarePulseT,
  VBlockBounce as VBlockBounceT, VBlockBreathe as VBlockBreatheT, VBlockCascade as VBlockCascadeT,
  VBlockPulse as VBlockPulseT, VBlockRain as VBlockRainT, VBlockRipple as VBlockRippleT,
  VBlockScanner as VBlockScannerT, VBlockTide as VBlockTideT, VBlockWave as VBlockWaveT,
} from "./pkg/agents_are_thinking_js";

export const EFFECTS: [
  typeof BrailleSpinT, typeof BrailleSpin2T, typeof BrailleWaveT, typeof BrailleRandomT,
  typeof BrailleBreatheT, typeof BrailleRippleT, typeof BrailleBounceT, typeof BrailleRainT,
  typeof BrailleZigzagT, typeof BrailleDissolveT, typeof BrailleFireT, typeof BrailleNoiseT,
  typeof BrailleHeartbeatT, typeof BrailleArrowT, typeof BrailleScannerT, typeof BrailleMatrixT,
  typeof BrailleCheckerboardT, typeof BrailleCheckerboard2x2T,
  typeof ShadeWaveT, typeof ShadeScannerT, typeof ShadeFireT, typeof ShadeRippleT,
  typeof ShadeBreatheT, typeof ShadeSeeSawT, typeof ShadeBlinkT, typeof ShadeLayersT, typeof ShadePinchT,
  typeof BarBounceT, typeof BarWaveT, typeof BarSeeSawT,
  typeof VBlockWaveT, typeof VBlockScannerT, typeof VBlockTideT, typeof VBlockBreatheT,
  typeof VBlockBounceT, typeof VBlockPulseT, typeof VBlockRippleT, typeof VBlockRainT, typeof VBlockCascadeT,
  typeof SquarePulseT, typeof SquareFillT, typeof SquareBlinkT, typeof SquareArrowT,
  typeof DotWaveT, typeof DotPulseT, typeof DotHeartbeatT, typeof DotArrowT, typeof DotBounceT,
];
