name: Publish Python package

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options: [major, minor, patch]

permissions:
  id-token: write
  pull-requests: read
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/agents_are_thinking_python
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v7
      - name: Setting up git config
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
          git config -l
      - name: Install bump-my-version
        run: uv tool install bump-my-version
      - name: Bump version
        id: bump
        run: |
          uv tool run bump-my-version bump ${{ inputs.release_type }}
          CURRENT_V=$(bump-my-version show current_version)
          echo "version=$CURRENT_V" >> $GITHUB_OUTPUT
      - name: Push Bump
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true

  linux:
    needs: bump
    runs-on: ${{ matrix.platform.runner }}
    defaults:
      run:
        working-directory: ./crates/agents_are_thinking_python
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          # - runner: ubuntu-22.04
          #   target: aarch64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./crates/agents_are_thinking_python
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: true
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-linux-${{ matrix.platform.target }}
          path: crates/agents_are_thinking_python/dist

  # musllinux:
  #   needs: bump
  #   runs-on: ${{ matrix.platform.runner }}
  #   strategy:
  #     matrix:
  #       platform:
  #         - runner: ubuntu-22.04
  #           target: x86_64
  #         - runner: ubuntu-22.04
  #           target: aarch64
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: actions/setup-python@v6
  #       with:
  #         python-version: 3.x
  #     - name: Build wheels
  #       uses: PyO3/maturin-action@v1
  #       with:
  #         target: ${{ matrix.platform.target }}
  #         args: --release --out dist --find-interpreter
  #         sccache: true
  #         manylinux: musllinux_1_2
  #     - name: Upload wheels
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: wheels-musllinux-${{ matrix.platform.target }}
  #         path: dist

  windows:
    needs: bump
    runs-on: ${{ matrix.platform.runner }}
    defaults:
      run:
        working-directory: ./crates/agents_are_thinking_python
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x64
            python_arch: x64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          architecture: ${{ matrix.platform.python_arch }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./crates/agents_are_thinking_python
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: true
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-windows-${{ matrix.platform.target }}
          path: crates/agents_are_thinking_python/dist

  macos:
    needs: bump
    runs-on: ${{ matrix.platform.runner }}
    defaults:
      run:
        working-directory: ./crates/agents_are_thinking_python
    strategy:
      matrix:
        platform:
          # - runner: macos-15-intel
          #   target: x86_64
          - runner: macos-latest
            target: aarch64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./crates/agents_are_thinking_python
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: true
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: crates/agents_are_thinking_python/dist

  sdist:
    needs: bump
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/agents_are_thinking_python
    steps:
      - uses: actions/checkout@v6
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./crates/agents_are_thinking_python
          command: sdist
          args: --out dist
      - name: Upload sdist
        uses: actions/upload-artifact@v6
        with:
          name: wheels-sdist
          path: crates/agents_are_thinking_python/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [linux, windows, macos, sdist]
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "dist/*"
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
      - name: GitHub Release py-v${{ needs.bump.outputs.version }}
        uses: ncipollo/release-action@v1
        with:
          name: agents-are-thinking py-v${{ needs.bump.outputs.version }}
          tag: py-v${{ needs.bump.outputs.version }}
          artifacts: "dist/*"
          token: ${{ secrets.GH_TOKEN }}
          generateReleaseNotes: true
