name: Publish Rust crate

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options: [major, minor, patch]

permissions:
  id-token: write
  pull-requests: read
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/agents_are_thinking
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Setting up git config
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
          git config -l
      # - name: Bump version
      #   id: bump
      #   uses: callowayproject/bump-my-version@master
      #   env:
      #     BUMPVERSION_TAG: "false"
      #   with:
      #     args: ${{ inputs.release_type }}
      #     github-token: ${{ secrets.GH_TOKEN }}
      - name: Install bump-my-version
        run: uv tool install bump-my-version
      - name: Bump version
        id: bump
        run: |
          uv tool run bump-my-version bump ${{ inputs.release_type }}
          CURRENT_V=$(bump-my-version show current_version)
          echo "version=$CURRENT_V" >> $GITHUB_OUTPUT
      - name: Push Bump
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: GitHub Release rs-v${{ steps.bump.outputs.version }}
        uses: ncipollo/release-action@v1
        with:
          name: agents-are-thinking rs-v${{ steps.bump.outputs.version }}
          tag: rs-v${{ steps.bump.outputs.version }}
          token: ${{ secrets.GH_TOKEN }}
          allowUpdates: true
          generateReleaseNotes: true

