from src.effects.base import Effect
from src.effects.braille_based import (
    BrailleSpin,
    BrailleSpin2,
    BrailleWave,
    BrailleRandom,
    BrailleBreathe,
    BrailleRipple,
    BrailleBounce,
    BrailleRain,
    BrailleZigzag,
    BrailleDissolve,
    BrailleFire,
    BrailleNoise,
    BrailleHeartbeat,
    BrailleArrow,
    BrailleScanner,
    BrailleMatrix,
)
from src.effects.progress import BlockProgress

EFFECTS: list[type[Effect]] = [
    BrailleSpin,
    BrailleSpin2,
    BrailleWave,
    BrailleRandom,
    BrailleBreathe,
    BrailleRipple,
    BrailleBounce,
    BrailleRain,
    BrailleZigzag,
    BrailleDissolve,
    BrailleFire,
    BlockProgress,
    BrailleNoise,
    BrailleHeartbeat,
    BrailleArrow,
    BrailleScanner,
    BrailleMatrix,
]
