from src.effects.base import Effect
from src.effects.braille_based import (
    BrailleSpin,
    BrailleSpin2,
    BrailleWave,
    BrailleRandom,
    BrailleBreathe,
    BrailleRipple,
    BrailleBounce,
    BrailleRain,
    BrailleZigzag,
    BrailleDissolve,
    BrailleFire,
    BrailleNoise,
    BrailleHeartbeat,
    BrailleArrow,
    BrailleScanner,
    BrailleMatrix,
    BrailleCheckerboard,
    BrailleCheckerboard2x2,
)
from src.effects.shade_based import (
    ShadeWave,
    ShadeScanner,
    ShadeFire,
    ShadePulse,
    ShadeBreathe,
)
from src.effects.bar_based import (
    BarEqualizer,
    BarWave,
)

EFFECTS: list[type[Effect]] = [
    BrailleSpin,
    BrailleSpin2,
    BrailleWave,
    BrailleRandom,
    BrailleBreathe,
    BrailleRipple,
    BrailleBounce,
    BrailleRain,
    BrailleZigzag,
    BrailleDissolve,
    BrailleFire,
    BrailleNoise,
    BrailleHeartbeat,
    BrailleArrow,
    BrailleScanner,
    BrailleMatrix,
    BrailleCheckerboard,
    BrailleCheckerboard2x2,
    ShadeWave,
    ShadeScanner,
    ShadeFire,
    ShadePulse,
    ShadeBreathe,
    BarEqualizer,
    BarWave,
]
